#! /usr/bin/env sh

DIR="$( cd "$( dirname "${0}" )" && pwd )"

mkdir -p "${HOME}/bin"

rm -rf "${HOME}/.sh_vars.sh"
rm -rf "${HOME}/.sh_fxns.sh"
rm -rf "${HOME}/.sh_exts.sh"
rm -rf "${HOME}/.sh_misc.sh"
rm -rf "${HOME}/perl-bits"
rm -rf "${HOME}/bin/basename_sort"
rm -rf "${HOME}/bin/clean"
rm -rf "${HOME}/bin/cless"
rm -rf "${HOME}/bin/copy"
rm -rf "${HOME}/bin/paste"
rm -rf "${HOME}/bin/pwdcp"
rm -rf "${HOME}/bin/suspend"
rm -rf "${HOME}/bin/trash"
rm -rf "${HOME}/bin/trim"

ln -s "${DIR}/.sh_vars.sh" "${HOME}/.sh_vars.sh"
ln -s "${DIR}/.sh_fxns.sh" "${HOME}/.sh_fxns.sh"
ln -s "${DIR}/.sh_exts.sh" "${HOME}/.sh_exts.sh"
ln -s "${DIR}/.sh_misc.sh" "${HOME}/.sh_misc.sh"
ln -s "${DIR}/perl-bits" "${HOME}/perl-bits"
ln -s "${DIR}/bin/basename_sort" "${HOME}/bin/basename_sort"
ln -s "${DIR}/bin/clean" "${HOME}/bin/clean"
ln -s "${DIR}/bin/cless" "${HOME}/bin/cless"
ln -s "${DIR}/bin/copy" "${HOME}/bin/copy"
ln -s "${DIR}/bin/paste" "${HOME}/bin/paste"
ln -s "${DIR}/bin/pwdcp" "${HOME}/bin/pwdcp"
ln -s "${DIR}/bin/suspend" "${HOME}/bin/suspend"
ln -s "${DIR}/bin/trash" "${HOME}/bin/trash"
ln -s "${DIR}/bin/trim" "${HOME}/bin/trim"

echo "Finished"
